# Generated by Django 3.2.9 on 2021-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0003_alter_brand_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='title',
            field=models.CharField(max_length=104, verbose_name='Название'),
        ),
    ]
