# Generated by Django 3.2.9 on 2021-11-30 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motorpool', '0004_auto_20211129_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-title'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
    ]
